# Generated by Django 5.0.2 on 2024-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(default='/images/auteur.jpg'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(default='/images/auteur.jpg'),
        ),
    ]
