# Generated by Django 5.0.2 on 2024-02-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_alter_customuser_email_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
