# Generated by Django 5.0.2 on 2024-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
