# Generated by Django 5.0.2 on 2024-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(default='/app/images/auteur.jpg'),
        ),
    ]
