# Generated by Django 5.0.2 on 2024-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(default='/static/images/auteur.jpg'),
        ),
    ]
