# Generated by Django 5.0.2 on 2024-02-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_author_alter_book_date_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
